/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ad-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available ad types */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/advertisers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all advertisers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_campaign.Advertiser"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get audit log */
        get: {
            parameters: {
                query?: {
                    /** @description Limit */
                    limit?: number;
                    /** @description Offset */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_audit.Entry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/circuit-break": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trip circuit breaker */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Trip reason */
            requestBody: {
                content: {
                    "application/json": {
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            reason?: string;
                            status?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/circuit-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset circuit breaker */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/circuit-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get circuit breaker status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            circuit_breaker?: string;
                            global_spend_today_cents?: number;
                            reason?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/creatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List creatives for review */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_campaign.Creative"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/creatives/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve creative */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Creative ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            status?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/creatives/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject creative */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Creative ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Body"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            status?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get system health */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            active_campaigns?: number;
                            status?: string;
                            time?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invite-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invite codes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_registration.InviteCode"][];
                    };
                };
            };
        };
        put?: never;
        /** Create invite code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Invite code config */
            requestBody: {
                content: {
                    "application/json": {
                        expires_at?: string;
                        max_uses?: number;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending registrations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_registration.Request"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/registrations/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve registration */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Registration ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            advertiser_id?: number;
                            api_key?: string;
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/registrations/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject registration */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Registration ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Body"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            status?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/topup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin top-up advertiser balance */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Body2"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_billing.Transaction"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/advertisers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create advertiser */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Advertiser data */
            requestBody: {
                content: {
                    "application/json": {
                        balance_cents?: number;
                        company_name?: string;
                        contact_email?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            api_key?: string;
                            id?: number;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/advertisers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get advertiser by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Advertiser ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_campaign.Advertiser"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get analytics snapshot */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Real-time analytics SSE stream */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get my audit log */
        get: {
            parameters: {
                query?: {
                    /** @description Limit */
                    limit?: number;
                    /** @description Offset */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_audit.Entry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List billing models */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/balance/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get advertiser balance */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Advertiser ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            advertiser_id?: number;
                            balance_cents?: number;
                            billing_type?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/topup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Top up advertiser balance */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Body2"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_billing.Transaction"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List billing transactions */
        get: {
            parameters: {
                query?: {
                    /** @description Advertiser ID */
                    advertiser_id?: number;
                    /** @description Limit */
                    limit?: number;
                    /** @description Offset */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_billing.Transaction"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List campaigns for advertiser */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_campaign.Campaign"][];
                    };
                };
            };
        };
        put?: never;
        /** Create campaign */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Campaign data */
            requestBody: {
                content: {
                    "application/json": {
                        advertiser_id?: number;
                        bid_cpm_cents?: number;
                        billing_model?: string;
                        budget_daily_cents?: number;
                        budget_total_cents?: number;
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get campaign by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Campaign ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_campaign.Campaign"];
                    };
                };
            };
        };
        /** Update campaign */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Campaign ID */
                    id: number;
                };
                cookie?: never;
            };
            /** @description Update fields */
            requestBody: {
                content: {
                    "application/json": {
                        bid_cpm_cents?: number;
                        budget_daily_cents?: number;
                        name?: string;
                        targeting?: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}/creatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List creatives for campaign */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Campaign ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_campaign.Creative"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause campaign */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Campaign ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start campaign */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Campaign ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create creative */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Creative data */
            requestBody: {
                content: {
                    "application/json": {
                        ad_markup?: string;
                        ad_type?: string;
                        campaign_id?: number;
                        destination_url?: string;
                        format?: string;
                        name?: string;
                        size?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creatives/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update creative */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Creative ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                        };
                    };
                };
            };
        };
        post?: never;
        /** Delete creative */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Creative ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            status?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/campaign/{id}/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export bid details as CSV */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Campaign ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/campaign/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export campaign stats as CSV */
        get: {
            parameters: {
                query?: {
                    /** @description Start date */
                    from?: string;
                    /** @description End date */
                    to?: string;
                };
                header?: never;
                path: {
                    /** @description Campaign ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit registration request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Registration data */
            requestBody: {
                content: {
                    "application/json": {
                        company_name?: string;
                        contact_email?: string;
                        invite_code?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            message?: string;
                            status?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/campaign/{id}/attribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get attribution report */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Campaign ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_reporting.AttributionReport"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/campaign/{id}/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get bid-level details */
        get: {
            parameters: {
                query?: {
                    /** @description Limit */
                    limit?: number;
                    /** @description Offset */
                    offset?: number;
                };
                header?: never;
                path: {
                    /** @description Campaign ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_reporting.BidDetail"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/campaign/{id}/geo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get geo breakdown */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Campaign ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_reporting.GeoStats"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/campaign/{id}/hourly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get hourly stats */
        get: {
            parameters: {
                query?: {
                    /** @description Date (YYYY-MM-DD) */
                    date?: string;
                };
                header?: never;
                path: {
                    /** @description Campaign ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_reporting.HourlyStats"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/campaign/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get campaign stats */
        get: {
            parameters: {
                query?: {
                    /** @description Start date (YYYY-MM-DD) */
                    from?: string;
                    /** @description End date (YYYY-MM-DD) */
                    to?: string;
                };
                header?: never;
                path: {
                    /** @description Campaign ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_heartgryphon_dsp_internal_reporting.CampaignStats"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get today overview stats */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            balance_cents?: number;
                            ctr?: number;
                            today_clicks?: number;
                            today_impressions?: number;
                            today_spend_cents?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload creative image */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description Image file
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            url?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "github_com_heartgryphon_dsp_internal_audit.Entry": {
            action?: string;
            actor?: string;
            advertiser_id?: number;
            created_at?: string;
            details?: {
                [key: string]: unknown;
            };
            id?: number;
            resource_id?: number;
            resource_type?: string;
        };
        "github_com_heartgryphon_dsp_internal_billing.Transaction": {
            advertiser_id?: number;
            amount_cents?: number;
            balance_after?: number;
            created_at?: string;
            description?: string;
            id?: number;
            reference_id?: string;
            type?: string;
        };
        "github_com_heartgryphon_dsp_internal_campaign.Advertiser": {
            active_campaigns?: number;
            api_key?: string;
            balance_cents?: number;
            billing_type?: string;
            company_name?: string;
            contact_email?: string;
            created_at?: string;
            id?: number;
            total_spent_cents?: number;
            updated_at?: string;
        };
        "github_com_heartgryphon_dsp_internal_campaign.Campaign": {
            advertiser_id?: number;
            bid_cpc_cents?: number;
            bid_cpm_cents?: number;
            billing_model?: string;
            budget_daily_cents?: number;
            budget_total_cents?: number;
            created_at?: string;
            end_date?: string;
            id?: number;
            name?: string;
            ocpm_target_cpa_cents?: number;
            pause_reason?: string;
            paused_at?: string;
            sandbox?: boolean;
            spent_cents?: number;
            start_date?: string;
            status?: components["schemas"]["github_com_heartgryphon_dsp_internal_campaign.Status"];
            targeting?: number[];
            updated_at?: string;
        };
        "github_com_heartgryphon_dsp_internal_campaign.Creative": {
            ad_markup?: string;
            ad_type?: string;
            campaign_id?: number;
            created_at?: string;
            destination_url?: string;
            format?: string;
            id?: number;
            name?: string;
            native_cta?: string;
            native_desc?: string;
            native_icon_url?: string;
            native_image_url?: string;
            /** @description Native ad fields (used when ad_type = "native") */
            native_title?: string;
            size?: string;
            status?: string;
        };
        /** @enum {string} */
        "github_com_heartgryphon_dsp_internal_campaign.Status": "draft" | "active" | "paused" | "completed" | "deleted";
        "github_com_heartgryphon_dsp_internal_registration.InviteCode": {
            code?: string;
            created_at?: string;
            created_by?: string;
            expires_at?: string;
            id?: number;
            max_uses?: number;
            used_count?: number;
        };
        "github_com_heartgryphon_dsp_internal_registration.Request": {
            business_type?: string;
            company_name?: string;
            contact_email?: string;
            contact_phone?: string;
            created_at?: string;
            id?: number;
            invite_code?: string;
            reject_reason?: string;
            reviewed_at?: string;
            reviewed_by?: string;
            status?: string;
            website?: string;
        };
        "github_com_heartgryphon_dsp_internal_reporting.AttributionReport": {
            campaign_id?: number;
            model?: string;
            paths?: components["schemas"]["github_com_heartgryphon_dsp_internal_reporting.ConversionPath"][];
            summary?: components["schemas"]["github_com_heartgryphon_dsp_internal_reporting.AttributionSummary"];
            total_conversions?: number;
            window?: string;
        };
        "github_com_heartgryphon_dsp_internal_reporting.AttributionSummary": {
            avg_time_to_convert?: string;
            avg_touchpoints?: number;
            /** @description conversions with a click in path */
            click_conversions?: number;
            /** @description conversions with impression only */
            view_conversions?: number;
        };
        "github_com_heartgryphon_dsp_internal_reporting.BidDetail": {
            bid_price_cents?: number;
            clear_price_cents?: number;
            device_os?: string;
            event_type?: string;
            geo_country?: string;
            loss_reason?: string;
            request_id?: string;
            time?: string;
        };
        "github_com_heartgryphon_dsp_internal_reporting.CampaignStats": {
            /** @description ADX settlement cost (cents) */
            adx_cost_cents?: number;
            bids?: number;
            campaign_id?: number;
            clicks?: number;
            conversions?: number;
            cpa?: number;
            ctr?: number;
            cvr?: number;
            impressions?: number;
            /** @description spend - adx_cost (cents) */
            profit_cents?: number;
            /** @description advertiser charge total (cents) */
            spend_cents?: number;
            win_rate?: number;
            wins?: number;
        };
        "github_com_heartgryphon_dsp_internal_reporting.ConversionPath": {
            campaign_id?: number;
            conversion_time?: string;
            credit?: components["schemas"]["github_com_heartgryphon_dsp_internal_reporting.CreditedEvent"][];
            device_id?: string;
            model?: string;
            touchpoints?: components["schemas"]["github_com_heartgryphon_dsp_internal_reporting.Touchpoint"][];
        };
        "github_com_heartgryphon_dsp_internal_reporting.CreditedEvent": {
            /** @description 0.0 - 1.0 */
            credit?: number;
            event_type?: string;
            request_id?: string;
        };
        "github_com_heartgryphon_dsp_internal_reporting.GeoStats": {
            clicks?: number;
            country?: string;
            impressions?: number;
            spend_cents?: number;
        };
        "github_com_heartgryphon_dsp_internal_reporting.HourlyStats": {
            clicks?: number;
            hour?: number;
            impressions?: number;
            spend_cents?: number;
        };
        "github_com_heartgryphon_dsp_internal_reporting.Touchpoint": {
            creative_id?: number;
            /** @description impression or click */
            event_type?: string;
            request_id?: string;
            time?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description Rejection reason */
        Body: {
            content: {
                "application/json": {
                    reason?: string;
                };
            };
        };
        /** @description Top-up data */
        Body2: {
            content: {
                "application/json": {
                    advertiser_id?: number;
                    amount_cents?: number;
                    description?: string;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
