global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "dsp-api"
    static_configs:
      - targets: ["host.docker.internal:8182"]

  - job_name: "dsp-bidder"
    static_configs:
      - targets: ["host.docker.internal:8180"]
