global:
  scrape_interval: 15s

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: "dsp-api"
    static_configs:
      - targets: ["api:8182"]

  - job_name: "dsp-bidder"
    static_configs:
      - targets: ["bidder:8180"]
